cmd_util/scripting-engines/trace-event-perl.o := gcc -Wp,-MD,util/scripting-engines/.trace-event-perl.o.d -Wp,-MT,util/scripting-engines/trace-event-perl.o -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wshadow -Iarch/arm64/include/generated -DHAVE_SYSCALL_TABLE_SUPPORT -DHAVE_PERF_REGS_SUPPORT -DHAVE_ARCH_REGS_QUERY_REGISTER_OFFSET -Werror -O6 -fno-omit-frame-pointer -ggdb3 -funwind-tables -Wall -Wextra -std=gnu99 -fstack-protector-all -D_FORTIFY_SOURCE=2 -I/users/ivy_wang/tools/perf/lib/include -I/users/ivy_wang/tools/perf/util/include -I/users/ivy_wang/tools/perf/arch/arm64/include -I/users/ivy_wang/tools/include/ -I/users/ivy_wang/tools/arch/arm64/include/uapi -I/users/ivy_wang/tools/include/uapi -I/users/ivy_wang/tools/arch/arm64/include/ -I/users/ivy_wang/tools/arch/arm64/ -I/users/ivy_wang/tools/perf/util -I/users/ivy_wang/tools/perf -I/users/ivy_wang/tools/lib/ -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DHAVE_SYNC_COMPARE_AND_SWAP_SUPPORT -DHAVE_PTHREAD_ATTR_SETAFFINITY_NP -DHAVE_PTHREAD_BARRIER -DHAVE_EVENTFD -DHAVE_GET_CURRENT_DIR_NAME -DHAVE_DWARF_GETLOCATIONS_SUPPORT -DHAVE_GLIBC_SUPPORT -DHAVE_AIO_SUPPORT -DHAVE_SCHED_GETCPU_SUPPORT -DHAVE_SETNS_SUPPORT -DHAVE_LIBELF_SUPPORT -DHAVE_LIBELF_MMAP_SUPPORT -DHAVE_ELF_GETPHDRNUM_SUPPORT -DHAVE_GELF_GETNOTE_SUPPORT -DHAVE_ELF_GETSHDRSTRNDX_SUPPORT -DHAVE_DWARF_SUPPORT -DHAVE_LIBBPF_SUPPORT -DHAVE_BPF_PROLOGUE -DHAVE_SDT_EVENT -DHAVE_JITDUMP -DHAVE_LIBUNWIND_AARCH64_SUPPORT -DHAVE_DWARF_UNWIND_SUPPORT -DHAVE_LIBUNWIND_SUPPORT -DHAVE_LIBCRYPTO_SUPPORT -DHAVE_SLANG_SUPPORT -DHAVE_GTK2_SUPPORT -DHAVE_LIBPERL_SUPPORT -DHAVE_TIMERFD_SUPPORT -DHAVE_LIBPYTHON_SUPPORT -DHAVE_CPLUS_DEMANGLE_SUPPORT -DHAVE_LIBBFD_SUPPORT -DHAVE_ZLIB_SUPPORT -DHAVE_LZMA_SUPPORT -DHAVE_ZSTD_SUPPORT -DHAVE_LIBCAP_SUPPORT -DHAVE_BACKTRACE_SUPPORT -DHAVE_LIBNUMA_SUPPORT -DDISASM_FOUR_ARGS_SIGNATURE -DHAVE_LIBBABELTRACE_SUPPORT -DHAVE_AUXTRACE_SUPPORT -D"BUILD_STR(s)=$(pound)s" -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/lib/aarch64-linux-gnu/perl/5.26/CORE -Wno-redundant-decls -Wno-strict-prototypes -Wno-unused-parameter -Wno-shadow -Wno-nested-externs -Wno-undef -Wno-switch-default -c -o util/scripting-engines/trace-event-perl.o util/scripting-engines/trace-event-perl.c

source_util/scripting-engines/trace-event-perl.o := util/scripting-engines/trace-event-perl.c

deps_util/scripting-engines/trace-event-perl.o := \
  /usr/include/stdc-predef.h \
  /usr/include/inttypes.h \
  /usr/include/features.h \
  /usr/include/aarch64-linux-gnu/sys/cdefs.h \
  /usr/include/aarch64-linux-gnu/bits/wordsize.h \
  /usr/include/aarch64-linux-gnu/bits/long-double.h \
  /usr/include/aarch64-linux-gnu/gnu/stubs.h \
  /usr/include/aarch64-linux-gnu/gnu/stubs-lp64.h \
  /usr/lib/gcc/aarch64-linux-gnu/7/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/aarch64-linux-gnu/bits/libc-header-start.h \
  /usr/include/aarch64-linux-gnu/bits/types.h \
  /usr/include/aarch64-linux-gnu/bits/typesizes.h \
  /usr/include/aarch64-linux-gnu/bits/wchar.h \
  /usr/include/aarch64-linux-gnu/bits/stdint-intn.h \
  /usr/include/aarch64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/stdio.h \
  /usr/lib/gcc/aarch64-linux-gnu/7/include/stddef.h \
  /usr/include/aarch64-linux-gnu/bits/types/__FILE.h \
  /usr/include/aarch64-linux-gnu/bits/types/FILE.h \
  /usr/include/aarch64-linux-gnu/bits/libio.h \
  /usr/include/aarch64-linux-gnu/bits/_G_config.h \
  /usr/include/aarch64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/lib/gcc/aarch64-linux-gnu/7/include/stdarg.h \
  /usr/include/aarch64-linux-gnu/bits/stdio_lim.h \
  /usr/include/aarch64-linux-gnu/bits/sys_errlist.h \
  /usr/include/aarch64-linux-gnu/bits/stdio.h \
  /usr/include/aarch64-linux-gnu/bits/stdio2.h \
  /usr/include/stdlib.h \
  /usr/include/aarch64-linux-gnu/bits/waitflags.h \
  /usr/include/aarch64-linux-gnu/bits/waitstatus.h \
  /usr/include/aarch64-linux-gnu/bits/floatn.h \
  /usr/include/aarch64-linux-gnu/bits/floatn-common.h \
  /usr/include/aarch64-linux-gnu/bits/types/locale_t.h \
  /usr/include/aarch64-linux-gnu/bits/types/__locale_t.h \
  /usr/include/aarch64-linux-gnu/sys/types.h \
  /usr/include/aarch64-linux-gnu/bits/types/clock_t.h \
  /usr/include/aarch64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/aarch64-linux-gnu/bits/types/time_t.h \
  /usr/include/aarch64-linux-gnu/bits/types/timer_t.h \
  /usr/include/endian.h \
  /usr/include/aarch64-linux-gnu/bits/endian.h \
  /usr/include/aarch64-linux-gnu/bits/byteswap.h \
  /usr/include/aarch64-linux-gnu/bits/byteswap-16.h \
  /usr/include/aarch64-linux-gnu/bits/uintn-identity.h \
  /usr/include/aarch64-linux-gnu/sys/select.h \
  /usr/include/aarch64-linux-gnu/bits/select.h \
  /usr/include/aarch64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/aarch64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/aarch64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/aarch64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/aarch64-linux-gnu/bits/select2.h \
  /usr/include/aarch64-linux-gnu/sys/sysmacros.h \
  /usr/include/aarch64-linux-gnu/bits/sysmacros.h \
  /usr/include/aarch64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/aarch64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/aarch64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/alloca.h \
  /usr/include/aarch64-linux-gnu/bits/stdlib-bsearch.h \
  /usr/include/aarch64-linux-gnu/bits/stdlib-float.h \
  /usr/include/aarch64-linux-gnu/bits/stdlib.h \
  /usr/include/string.h \
  /usr/include/strings.h \
  /usr/include/aarch64-linux-gnu/bits/strings_fortified.h \
  /usr/include/aarch64-linux-gnu/bits/string_fortified.h \
  /usr/include/ctype.h \
  /usr/include/errno.h \
  /usr/include/aarch64-linux-gnu/bits/errno.h \
  /usr/include/linux/errno.h \
  /users/ivy_wang/tools/include/uapi/asm/errno.h \
  /users/ivy_wang/tools/include/uapi/asm-generic/errno.h \
  /users/ivy_wang/tools/include/uapi/asm-generic/errno-base.h \
  /users/ivy_wang/tools/include/linux/bitmap.h \
  /users/ivy_wang/tools/include/linux/bitops.h \
  /usr/include/aarch64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /users/ivy_wang/tools/arch/arm64/include/uapi/asm/bitsperlong.h \
  /users/ivy_wang/tools/include/asm-generic/bitsperlong.h \
  /users/ivy_wang/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/lib/gcc/aarch64-linux-gnu/7/include-fixed/limits.h \
  /usr/lib/gcc/aarch64-linux-gnu/7/include-fixed/syslimits.h \
  /usr/include/limits.h \
  /usr/include/aarch64-linux-gnu/bits/posix1_lim.h \
  /usr/include/aarch64-linux-gnu/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/aarch64-linux-gnu/bits/posix2_lim.h \
  /usr/include/aarch64-linux-gnu/bits/xopen_lim.h \
  /usr/include/aarch64-linux-gnu/bits/uio_lim.h \
  /users/ivy_wang/tools/include/linux/bits.h \
  /users/ivy_wang/tools/include/linux/const.h \
  /users/ivy_wang/tools/include/uapi/linux/const.h \
  /users/ivy_wang/tools/include/linux/compiler.h \
  /users/ivy_wang/tools/include/linux/compiler-gcc.h \
  /users/ivy_wang/tools/include/linux/types.h \
  /usr/lib/gcc/aarch64-linux-gnu/7/include/stdbool.h \
  /usr/include/aarch64-linux-gnu/asm/posix_types.h \
  /usr/include/asm-generic/posix_types.h \
  /users/ivy_wang/tools/include/asm-generic/bitops.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/__ffs.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/__ffz.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/fls.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/__fls.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/fls64.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/find.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/hweight.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/arch_hweight.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/const_hweight.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/atomic.h \
  /users/ivy_wang/tools/include/asm-generic/bitops/non-atomic.h \
  /users/ivy_wang/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /usr/include/byteswap.h \
  /users/ivy_wang/tools/include/linux/time64.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/EXTERN.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/perl.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/config.h \
  /usr/include/locale.h \
  /usr/include/aarch64-linux-gnu/bits/locale.h \
  /usr/include/setjmp.h \
  /usr/include/aarch64-linux-gnu/bits/setjmp.h \
  /usr/include/aarch64-linux-gnu/bits/setjmp2.h \
  /usr/include/aarch64-linux-gnu/sys/param.h \
  /usr/include/signal.h \
  /usr/include/aarch64-linux-gnu/bits/signum.h \
  /usr/include/aarch64-linux-gnu/bits/signum-generic.h \
  /usr/include/aarch64-linux-gnu/bits/types/sig_atomic_t.h \
  /usr/include/aarch64-linux-gnu/bits/types/siginfo_t.h \
  /usr/include/aarch64-linux-gnu/bits/types/__sigval_t.h \
  /usr/include/aarch64-linux-gnu/bits/siginfo-arch.h \
  /usr/include/aarch64-linux-gnu/bits/siginfo-consts.h \
  /usr/include/aarch64-linux-gnu/bits/siginfo-consts-arch.h \
  /usr/include/aarch64-linux-gnu/bits/types/sigval_t.h \
  /usr/include/aarch64-linux-gnu/bits/types/sigevent_t.h \
  /usr/include/aarch64-linux-gnu/bits/sigevent-consts.h \
  /usr/include/aarch64-linux-gnu/bits/sigaction.h \
  /usr/include/aarch64-linux-gnu/bits/sigcontext.h \
  /usr/include/aarch64-linux-gnu/asm/sigcontext.h \
  /usr/include/aarch64-linux-gnu/bits/types/stack_t.h \
  /usr/include/aarch64-linux-gnu/sys/ucontext.h \
  /usr/include/aarch64-linux-gnu/sys/procfs.h \
  /usr/include/aarch64-linux-gnu/sys/time.h \
  /usr/include/aarch64-linux-gnu/sys/user.h \
  /usr/include/aarch64-linux-gnu/bits/sigstack.h \
  /usr/include/aarch64-linux-gnu/bits/ss_flags.h \
  /usr/include/aarch64-linux-gnu/bits/types/struct_sigstack.h \
  /usr/include/aarch64-linux-gnu/bits/sigthread.h \
  /usr/include/aarch64-linux-gnu/bits/param.h \
  /usr/include/linux/param.h \
  /usr/include/aarch64-linux-gnu/asm/param.h \
  /usr/include/asm-generic/param.h \
  /usr/include/unistd.h \
  /usr/include/aarch64-linux-gnu/bits/posix_opt.h \
  /usr/include/aarch64-linux-gnu/bits/environments.h \
  /usr/include/aarch64-linux-gnu/bits/confname.h \
  /usr/include/aarch64-linux-gnu/bits/getopt_posix.h \
  /usr/include/aarch64-linux-gnu/bits/getopt_core.h \
  /usr/include/aarch64-linux-gnu/bits/unistd.h \
  /usr/include/aarch64-linux-gnu/sys/wait.h \
  /usr/include/netinet/in.h \
  /usr/include/aarch64-linux-gnu/sys/socket.h \
  /usr/include/aarch64-linux-gnu/bits/types/struct_iovec.h \
  /usr/include/aarch64-linux-gnu/bits/socket.h \
  /usr/include/aarch64-linux-gnu/bits/socket_type.h \
  /usr/include/aarch64-linux-gnu/bits/sockaddr.h \
  /usr/include/aarch64-linux-gnu/asm/socket.h \
  /users/ivy_wang/tools/include/uapi/asm-generic/socket.h \
  /usr/include/linux/posix_types.h \
  /usr/include/linux/stddef.h \
  /usr/include/aarch64-linux-gnu/asm/sockios.h \
  /usr/include/asm-generic/sockios.h \
  /usr/include/aarch64-linux-gnu/bits/types/struct_osockaddr.h \
  /usr/include/aarch64-linux-gnu/bits/socket2.h \
  /usr/include/aarch64-linux-gnu/bits/in.h \
  /usr/include/arpa/inet.h \
  /usr/include/aarch64-linux-gnu/sys/stat.h \
  /usr/include/aarch64-linux-gnu/bits/stat.h \
  /usr/include/time.h \
  /usr/include/aarch64-linux-gnu/bits/time.h \
  /usr/include/aarch64-linux-gnu/bits/timex.h \
  /usr/include/aarch64-linux-gnu/bits/types/struct_tm.h \
  /usr/include/aarch64-linux-gnu/bits/types/struct_itimerspec.h \
  /usr/include/aarch64-linux-gnu/sys/times.h \
  /usr/include/netdb.h \
  /usr/include/rpc/netdb.h \
  /usr/include/aarch64-linux-gnu/bits/netdb.h \
  /usr/include/aarch64-linux-gnu/sys/ioctl.h \
  /usr/include/aarch64-linux-gnu/bits/ioctls.h \
  /usr/include/aarch64-linux-gnu/asm/ioctls.h \
  /users/ivy_wang/tools/include/uapi/asm-generic/ioctls.h \
  /usr/include/linux/ioctl.h \
  /usr/include/aarch64-linux-gnu/asm/ioctl.h \
  /usr/include/asm-generic/ioctl.h \
  /usr/include/aarch64-linux-gnu/bits/ioctl-types.h \
  /usr/include/aarch64-linux-gnu/sys/ttydefaults.h \
  /usr/include/dirent.h \
  /usr/include/aarch64-linux-gnu/bits/dirent.h \
  /usr/lib/gcc/aarch64-linux-gnu/7/include/float.h \
  /usr/include/math.h \
  /usr/include/aarch64-linux-gnu/bits/math-vector.h \
  /usr/include/aarch64-linux-gnu/bits/libm-simd-decl-stubs.h \
  /usr/include/aarch64-linux-gnu/bits/flt-eval-method.h \
  /usr/include/aarch64-linux-gnu/bits/fp-logb.h \
  /usr/include/aarch64-linux-gnu/bits/fp-fast.h \
  /usr/include/aarch64-linux-gnu/bits/mathcalls-helper-functions.h \
  /usr/include/aarch64-linux-gnu/bits/mathcalls.h \
  /usr/include/aarch64-linux-gnu/bits/iscanonical.h \
  /usr/include/aarch64-linux-gnu/bits/mathinline.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/handy.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/charclass_invlists.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/unixish.h \
  /usr/include/pthread.h \
  /usr/include/sched.h \
  /usr/include/aarch64-linux-gnu/bits/sched.h \
  /usr/include/aarch64-linux-gnu/bits/cpu-set.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/iperlsys.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/perlio.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/perly.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/sv.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/regexp.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/utf8.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/regcharclass.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/unicode_constants.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/op_reg_common.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/util.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/form.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/gv.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/pad.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/cv.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/opnames.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/op.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/reentr.h \
  /usr/include/pwd.h \
  /usr/include/grp.h \
  /usr/include/crypt.h \
  /usr/include/shadow.h \
  /usr/include/paths.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/hv.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/hv_func.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/cop.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/mydtrace.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/av.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/mg.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/scope.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/warnings.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/parser.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/patchlevel.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/intrpvar.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/thread.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/pp.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/proto.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/opcode.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/embedvar.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/embed.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/perlvars.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/mg_vtable.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/inline.h \
  /usr/lib/aarch64-linux-gnu/perl/5.26/CORE/overload.h \
  /usr/include/aarch64-linux-gnu/sys/ipc.h \
  /usr/include/aarch64-linux-gnu/bits/ipctypes.h \
  /usr/include/aarch64-linux-gnu/bits/ipc.h \
  /usr/include/aarch64-linux-gnu/sys/sem.h \
  /usr/include/aarch64-linux-gnu/bits/sem.h \
  /usr/include/aarch64-linux-gnu/sys/file.h \
  /usr/include/fcntl.h \
  /usr/include/aarch64-linux-gnu/bits/fcntl.h \
  /usr/include/aarch64-linux-gnu/bits/fcntl-linux.h \
  /usr/include/linux/falloc.h \
  /usr/include/aarch64-linux-gnu/bits/fcntl2.h \
  util/scripting-engines/../callchain.h \
  /users/ivy_wang/tools/include/linux/list.h \
  /users/ivy_wang/tools/include/linux/poison.h \
  /users/ivy_wang/tools/include/linux/rbtree.h \
  util/scripting-engines/../map_symbol.h \
  util/scripting-engines/../branch.h \
  /users/ivy_wang/tools/include/uapi/linux/perf_event.h \
  /usr/include/aarch64-linux-gnu/asm/byteorder.h \
  /usr/include/linux/byteorder/little_endian.h \
  /usr/include/linux/swab.h \
  /users/ivy_wang/tools/perf/util/include/asm/swab.h \
  util/scripting-engines/../dso.h \
  /users/ivy_wang/tools/include/linux/refcount.h \
  /users/ivy_wang/tools/include/linux/atomic.h \
  /users/ivy_wang/tools/include/asm/atomic.h \
  /users/ivy_wang/tools/include/asm-generic/atomic-gcc.h \
  util/scripting-engines/../build-id.h \
  util/scripting-engines/../tool.h \
  util/scripting-engines/../machine.h \
  util/scripting-engines/../map_groups.h \
  util/scripting-engines/../rwsem.h \
  util/scripting-engines/../dsos.h \
  util/scripting-engines/../map.h \
  util/scripting-engines/../symbol.h \
  util/scripting-engines/../path.h \
  util/scripting-engines/../symbol_conf.h \
  /usr/include/libelf.h \
  /usr/include/elf.h \
  /usr/include/aarch64-linux-gnu/bits/auxv.h \
  /usr/include/gelf.h \
  util/scripting-engines/../thread.h \
  util/scripting-engines/../srccode.h \
  /users/ivy_wang/tools/perf/util/strlist.h \
  /users/ivy_wang/tools/perf/util/rblist.h \
  /users/ivy_wang/tools/perf/util/intlist.h \
  util/scripting-engines/../event.h \
  /users/ivy_wang/tools/perf/lib/include/perf/event.h \
  /users/ivy_wang/tools/include/uapi/linux/bpf.h \
  /users/ivy_wang/tools/include/uapi/linux/bpf_common.h \
  util/scripting-engines/../perf_regs.h \
  /users/ivy_wang/tools/perf/arch/arm64/include/perf_regs.h \
  /users/ivy_wang/tools/arch/arm64/include/uapi/asm/perf_regs.h \
  util/scripting-engines/../trace-event.h \
  /users/ivy_wang/tools/lib/traceevent/event-parse.h \
  /usr/include/regex.h \
  /users/ivy_wang/tools/lib/traceevent/trace-seq.h \
  util/scripting-engines/../parse-events.h \
  util/scripting-engines/../evsel.h \
  /users/ivy_wang/tools/perf/lib/include/internal/evsel.h \
  /users/ivy_wang/tools/perf/lib/include/perf/evsel.h \
  /users/ivy_wang/tools/perf/lib/include/perf/core.h \
  /users/ivy_wang/tools/perf/lib/include/internal/cpumap.h \
  util/scripting-engines/../debug.h \

util/scripting-engines/trace-event-perl.o: $(deps_util/scripting-engines/trace-event-perl.o)

$(deps_util/scripting-engines/trace-event-perl.o):
